# sentinel_project_root/pages/glossary_page.py
# Glossary of Terms for the "Sentinel Health Co-Pilot" System.

import streamlit as st
import logging
from typing import Optional, Any, Union, Dict, List # Added Union, Dict, List
import html # For escaping

from config import settings

logger = logging.getLogger(__name__)

st.title(f"📜 {settings.APP_NAME} - Glossary of Terms")
st.markdown(
    "Definitions for common terms, abbreviations, metrics, and system-specific concepts "
    "used throughout the Sentinel Health Co-Pilot platform."
)
st.divider()

def _display_glossary_term(
    term_name: str,
    definition_text: str,
    related_config_variable_name: Optional[str] = None
) -> None:
    """ Displays a glossary term and its definition in a standardized format. """
    st.markdown(f"#### {html.escape(term_name)}") # Escape term name
    st.markdown(f"*{html.escape(definition_text)}*") # Escape definition
    
    if related_config_variable_name:
        config_value_display: Optional[Any] = None
        try:
            config_value_display = getattr(settings, related_config_variable_name, None)
        except AttributeError: # Should not happen with getattr's default
            pass # config_value_display remains None

        display_val_str = "Not Found/Error"
        if config_value_display is not None:
            if isinstance(config_value_display, list):
                # Show first few elements for lists to avoid long displays
                display_val_str = ", ".join(map(str, config_value_display[:min(5, len(config_value_display))]))
                if len(config_value_display) > 5: display_val_str += ", ..."
            elif isinstance(config_value_display, dict):
                # Show first few items for dicts
                dict_items_preview = list(config_value_display.items())[:min(2, len(config_value_display))]
                display_val_str = f"{ {k:v for k,v in dict_items_preview} }"
                if len(config_value_display) > 2: display_val_str = display_val_str[:-1] + ", ...}"
            else:
                display_val_str = str(config_value_display)
            
            # Truncate very long strings (like paths) for display
            if len(display_val_str) > 150: display_val_str = display_val_str[:147] + "..."
        else: # getattr returned None
             display_val_str = f"(config '{related_config_variable_name}' not found in settings)"
        
        st.caption(f"*(Related config: `settings.{html.escape(related_config_variable_name)}` = `{html.escape(display_val_str)}`)*")
    st.markdown("---")


# --- Section I: Sentinel Health Co-Pilot System Concepts ---
st.header("🌐 System Architecture & Core Concepts")
_display_glossary_term(
    "Sentinel Health Co-Pilot", 
    "An edge-first health intelligence and action support system for resource-limited, high-risk LMIC environments, prioritizing offline functionality, actionable insights for frontline health workers (FHWs), and resilient data flow."
)
_display_glossary_term(
    "Personal Edge Device (PED)", 
    "A ruggedized smartphone, wearable, or low-power SoC used by FHWs. Runs native apps with on-device Edge AI for real-time monitoring, alerts, task management, and JIT guidance, primarily offline."
)
_display_glossary_term(
    "Edge AI / TinyML", 
    "AI models (e.g., TFLite) optimized for PEDs or local Supervisor Hubs, enabling offline decision support, anomaly detection, and risk stratification with minimal resources."
)
_display_glossary_term(
    "Supervisor Hub (Tier 1)", 
    "Optional intermediary device for CHW Supervisors. Locally aggregates PED data, allows localized team oversight, and batches data for Facility Nodes.",
    "HUB_SQLITE_DB_NAME"
)
_display_glossary_term(
    "Facility Node (Tier 2)", 
    "Local server/PC at a clinic. Aggregates data from Hubs/PEDs, performs local analytics, interfaces with EMRs, generates reports, and stages data for wider sync.",
    "FACILITY_NODE_DB_TYPE"
)
_display_glossary_term(
    "Regional/Cloud Node (Tier 3)", 
    "Optional centralized infrastructure for population-level analytics, AI model training, and national reporting. Receives data from Facility Nodes."
)
_display_glossary_term(
    "Lean Data Inputs", 
    f"Core principle: collect minimal viable data with maximum predictive power for Edge AI and FHW actionability in LMIC settings (e.g., age group, chronic condition flag, SpO₂ < {settings.ALERT_SPO2_CRITICAL_LOW_PCT}%, observed fatigue, key symptoms).",
    "ALERT_SPO2_CRITICAL_LOW_PCT"
)
_display_glossary_term(
    "Action Code / Suggested Action Code", 
    "System-internal code (e.g., 'ACTION_SPO2_MANAGE_URGENT') generated by alerts, AI, or tasks. Maps to PED UI elements (pictograms, guidance) via configuration files.",
    "PICTOGRAM_MAP_JSON_PATH"
)
_display_glossary_term(
    "Opportunistic Sync", 
    "Data synchronization strategy where devices transfer data to higher tiers only when a viable, low-cost, stable communication channel is available (e.g., Bluetooth, local Wi-Fi, QR).",
    "EDGE_DATA_SYNC_PROTOCOLS_SUPPORTED"
)

# --- Section II: Clinical, Epidemiological & Operational Terms ---
st.header("🩺 Clinical, Epidemiological & Operational Terms")
_display_glossary_term(
    "AI Risk Score (Patient/Worker)", 
    f"Simulated algorithmic score (0-100) predicting health risk or adverse outcome likelihood. High Risk ≥ {settings.RISK_SCORE_HIGH_THRESHOLD}.", 
    "RISK_SCORE_HIGH_THRESHOLD"
)
_display_glossary_term(
    "AI Follow-up Priority Score / Task Priority Score", 
    f"Simulated score (0-100) from AI/rules to prioritize patient follow-ups or tasks. High priority e.g., ≥ {settings.FATIGUE_INDEX_HIGH_THRESHOLD}.", 
    "FATIGUE_INDEX_HIGH_THRESHOLD"
)
_display_glossary_term(
    "Ambient Heat Index (°C)", 
    f"Perceived heat combining humidity and air temperature. Sentinel alerts: Risk at {settings.ALERT_AMBIENT_HEAT_INDEX_RISK_C}°C, Danger at {settings.ALERT_AMBIENT_HEAT_INDEX_DANGER_C}°C.", 
    "ALERT_AMBIENT_HEAT_INDEX_DANGER_C"
)
_display_glossary_term(
    "Condition (Key Actionable)", 
    f"Specific health conditions prioritized by Sentinel for monitoring, alerts, and response protocols. Defined in `settings.KEY_CONDITIONS_FOR_ACTION` (e.g., '{settings.KEY_CONDITIONS_FOR_ACTION[0] if settings.KEY_CONDITIONS_FOR_ACTION else 'TB'}').", 
    "KEY_CONDITIONS_FOR_ACTION"
)
_display_glossary_term(
    "Encounter (CHW/Clinic)", 
    "Any patient interaction with the health system or CHW documented in Sentinel (home visits, clinic consults, alert responses, follow-ups, remote check-ins)."
)
_display_glossary_term(
    "Facility Coverage Score (Zonal)", 
    f"District-level metric (0-100%) of health facility access/capacity relative to zone population. Low coverage (e.g., < {settings.DISTRICT_INTERVENTION_FACILITY_COVERAGE_LOW_PCT}%) may trigger DHO review.", 
    "DISTRICT_INTERVENTION_FACILITY_COVERAGE_LOW_PCT"
)
_display_glossary_term(
    "Fatigue Index Score (Worker)", 
    f"Simulated score (0-100) of FHW fatigue, derived by Edge AI from HRV, activity, or self-reports. Alerts: Moderate ≥ {settings.FATIGUE_INDEX_MODERATE_THRESHOLD}, High ≥ {settings.FATIGUE_INDEX_HIGH_THRESHOLD}.", 
    "FATIGUE_INDEX_HIGH_THRESHOLD"
)
_display_glossary_term(
    "HRV (Heart Rate Variability)", 
    f"Variation in time between heartbeats (ms, e.g., RMSSD). Low HRV (e.g., < {settings.STRESS_HRV_LOW_THRESHOLD_MS}ms) can indicate increased physiological stress/fatigue.",
    "STRESS_HRV_LOW_THRESHOLD_MS"
)
_display_glossary_term(
    "SpO₂ (Peripheral Capillary Oxygen Saturation)", 
    f"Estimate of blood oxygen saturation (%). Critical Low: < {settings.ALERT_SPO2_CRITICAL_LOW_PCT}%. Warning Low: < {settings.ALERT_SPO2_WARNING_LOW_PCT}%.", 
    "ALERT_SPO2_CRITICAL_LOW_PCT"
)
_display_glossary_term(
    "TAT (Test Turnaround Time)", 
    f"Time from sample collection/registration to result availability. General critical test target ~{settings.TARGET_TEST_TURNAROUND_DAYS} days. Specifics in `settings.KEY_TEST_TYPES_FOR_ANALYSIS`.", 
    "TARGET_TEST_TURNAROUND_DAYS"
)

# --- Section III: Technical & Data Format Terms ---
st.header("💻 Technical, Data & Platform Terms")
_display_glossary_term(
    "API (Application Programming Interface)", 
    "Rules/protocols for software communication. Used in Sentinel for data sync between tiers (e.g., Facility to Regional) or external system integration (e.g., DHIS2, EMRs).",
    "FHIR_SERVER_ENDPOINT_LOCAL"
)
_display_glossary_term(
    "CSV (Comma-Separated Values)", 
    "Simple text file format for tabular data. Used for raw data import (e.g., health records) and simple reporting.",
    "HEALTH_RECORDS_CSV_PATH"
)
_display_glossary_term(
    "FHIR (Fast Healthcare Interoperability Resources)", 
    "Pronounced 'Fire'. HL7® international standard for exchanging EHRs using 'Resources' and an API. Sentinel aims for FHIR support at Tiers 2 & 3.",
    "FHIR_SERVER_ENDPOINT_LOCAL"
)
_display_glossary_term(
    "GeoJSON", 
    f"Open standard JSON-based format for encoding geographic data (points, lines, polygons) and attributes. Used for operational zone boundaries. Default CRS: {settings.DEFAULT_CRS_STANDARD}.",
    "ZONE_GEOMETRIES_GEOJSON_FILE_PATH"
)
_display_glossary_term(
    "JSON (JavaScript Object Notation)", 
    "Lightweight, human-readable data-interchange format. Used for configuration files (e.g., escalation protocols) and API data exchange.",
    "ESCALATION_PROTOCOLS_JSON_PATH"
)
_display_glossary_term(
    "Pictogram", 
    "Simple iconic image representing a concept, action, or object. Used in Sentinel PED UIs for clarity, especially for low-literacy users or multilingual contexts. Mapped via configuration.",
    "PICTOGRAM_MAP_JSON_PATH"
)
_display_glossary_term(
    "QR Code Packet", 
    f"Method for offline data transfer by encoding data into QR codes. Useful for PED-to-Hub/PED-to-PED exchange. Max single packet size: {settings.QR_PACKET_MAX_SIZE_BYTES} bytes.",
    "QR_PACKET_MAX_SIZE_BYTES"
)
_display_glossary_term(
    "SQLite", 
    "Embedded SQL database engine. Used in Sentinel for local data storage on PEDs and Supervisor Hubs due to portability and no need for a separate server.",
    "PED_SQLITE_DB_NAME"
)
_display_glossary_term(
    "TFLite (TensorFlow Lite)", 
    "Open-source deep learning framework for running TensorFlow models on mobile, embedded, and IoT devices. Key for Edge AI on Sentinel PEDs.",
    "EDGE_MODEL_VITALS_DETERIORATION"
)

st.divider()
st.caption(settings.APP_FOOTER_TEXT)
logger.info(f"Glossary page for {settings.APP_NAME} (v{settings.APP_VERSION}) loaded.")
