# sentinel_project_root/pages/05_System_Glossary.py
# SME PLATINUM STANDARD - GLOSSARY PAGE

import html
import logging

import streamlit as st
from config import settings

# --- Page Setup ---
st.set_page_config(page_title="Glossary", page_icon="📜", layout="wide")
logger = logging.getLogger(__name__)

# --- Helper Function ---
def display_term(term: str, definition: str, config_key: str = None):
    st.markdown(f"#### {html.escape(term)}")
    st.markdown(f"*{html.escape(definition)}*")
    
    if config_key and hasattr(settings, config_key):
        value = getattr(settings, config_key, "Not Found")
        if isinstance(value, (list, dict)) and len(str(value)) > 100:
            value_str = f"{str(value)[:100]}..."
        else:
            value_str = str(value)
        st.caption(f"`settings.{config_key}` = `{html.escape(value_str)}`")
    elif config_key:
        st.caption(f"`settings.{config_key}` (Not found in current config)")
    st.markdown("---")


st.header("🌐 System Architecture & Core Concepts", anchor="system-architecture-core-concepts")
# Using hasattr for all settings access in f-strings for robustness
spo2_critical_low_setting = settings.ALERT_SPO2_CRITICAL_LOW_PCT if hasattr(settings, 'ALERT_SPO2_CRITICAL_LOW_PCT') else 'N/A'

_display_glossary_term(
    "Sentinel Health Co-Pilot", 
    "An edge-first health intelligence and action support system for resource-limited, high-risk LMIC environments, prioritizing offline functionality, actionable insights for frontline health workers (FHWs), and resilient data flow."
)
_display_glossary_term(
    "Personal Edge Device (PED)", 
    "A ruggedized smartphone, wearable, or low-power SoC used by FHWs. Runs native apps with on-device Edge AI for real-time monitoring, alerts, task management, and JIT guidance, primarily offline."
)
_display_glossary_term(
    "Edge AI / TinyML", 
    "AI models (e.g., TFLite) optimized for PEDs or local Supervisor Hubs, enabling offline decision support, anomaly detection, and risk stratification with minimal resources."
)
_display_glossary_term(
    "Supervisor Hub (Tier 1)", 
    "Optional intermediary device for CHW Supervisors. Locally aggregates PED data, allows localized team oversight, and batches data for Facility Nodes.",
    "HUB_SQLITE_DB_NAME" 
)
_display_glossary_term(
    "Facility Node (Tier 2)", 
    "Local server/PC at a clinic. Aggregates data from Hubs/PEDs, performs local analytics, interfaces with EMRs, generates reports, and stages data for wider sync.",
    "FACILITY_NODE_DB_TYPE" 
)
_display_glossary_term(
    "Regional/Cloud Node (Tier 3)", 
    "Optional centralized infrastructure for population-level analytics, AI model training, and national reporting. Receives data from Facility Nodes."
)
_display_glossary_term(
    "Lean Data Inputs", 
    f"Core principle: collect minimal viable data with maximum predictive power for Edge AI and FHW actionability in LMIC settings (e.g., age group, chronic condition flag, SpO₂ < {spo2_critical_low_setting}%, observed fatigue, key symptoms).",
    "ALERT_SPO2_CRITICAL_LOW_PCT"
)
_display_glossary_term(
    "Action Code / Suggested Action Code", 
    "System-internal code (e.g., 'ACTION_SPO2_MANAGE_URGENT') generated by alerts, AI, or tasks. Maps to PED UI elements (pictograms, guidance) via configuration files.",
    "PICTOGRAM_MAP_JSON_PATH" 
)
_display_glossary_term(
    "Opportunistic Sync", 
    "Data synchronization strategy where devices transfer data to higher tiers only when a viable, low-cost, stable communication channel is available (e.g., Bluetooth, local Wi-Fi, QR).",
    "EDGE_DATA_SYNC_PROTOCOLS_SUPPORTED" 
)

_display_glossary_term(
    "AI Risk Score (Patient/Worker)", 
    f"Simulated algorithmic score (0-100) predicting health risk or adverse outcome likelihood. High Risk ≥ {risk_score_high_setting}.", 
    "RISK_SCORE_HIGH_THRESHOLD"
)
_display_glossary_term(
    "AI Follow-up Priority Score / Task Priority Score", 
    f"Simulated score (0-100) from AI/rules to prioritize patient follow-ups or tasks. High priority e.g., ≥ {fatigue_high_setting}.", 
    "FATIGUE_INDEX_HIGH_THRESHOLD"
)
_display_glossary_term(
    "Ambient Heat Index (°C)", 
    f"Perceived heat combining humidity and air temperature. Sentinel alerts: Risk at {heat_risk_setting}°C, Danger at {heat_danger_setting}°C.", 
    "ALERT_AMBIENT_HEAT_INDEX_DANGER_C"
)
_display_glossary_term(
    "Condition (Key Actionable)", 
    f"Specific health conditions prioritized by Sentinel for monitoring, alerts, and response protocols. Defined in `settings.KEY_CONDITIONS_FOR_ACTION` (e.g., '{key_condition_example}').", 
    "KEY_CONDITIONS_FOR_ACTION"
)
_display_glossary_term(
    "Encounter (CHW/Clinic)", 
    "Any patient interaction with the health system or CHW documented in Sentinel (home visits, clinic consults, alert responses, follow-ups, remote check-ins)."
)
_display_glossary_term(
    "Facility Coverage Score (Zonal)", 
    f"District-level metric (0-100%) of health facility access/capacity relative to zone population. Low coverage (e.g., < {facility_coverage_low_setting}%) may trigger DHO review.", 
    "DISTRICT_INTERVENTION_FACILITY_COVERAGE_LOW_PCT"
)
_display_glossary_term(
    "Fatigue Index Score (Worker)", 
    f"Simulated score (0-100) of FHW fatigue, derived by Edge AI from HRV, activity, or self-reports. Alerts: Moderate ≥ {fatigue_moderate_setting}, High ≥ {fatigue_high_setting}.", 
    "FATIGUE_INDEX_HIGH_THRESHOLD"
)
_display_glossary_term(
    "HRV (Heart Rate Variability)", 
    f"Variation in time between heartbeats (ms, e.g., RMSSD). Low HRV (e.g., < {hrv_low_setting}ms) can indicate increased physiological stress/fatigue.",
    "STRESS_HRV_LOW_THRESHOLD_MS"
)
_display_glossary_term(
    "SpO₂ (Peripheral Capillary Oxygen Saturation)", 
    f"Estimate of blood oxygen saturation (%). Critical Low: < {spo2_critical_low_setting}%. Warning Low: < {spo2_warn_low_setting}%.", 
    "ALERT_SPO2_CRITICAL_LOW_PCT"
)
_display_glossary_term(
    "TAT (Test Turnaround Time)", 
    f"Time from sample collection/registration to result availability. General critical test target ~{tat_target_setting} days. Specifics in `settings.KEY_TEST_TYPES_FOR_ANALYSIS`.", 
    "TARGET_TEST_TURNAROUND_DAYS"
)

st.header("💻 Technical, Data & Platform Terms", anchor="technical-data-platform-terms")
default_crs_setting = settings.DEFAULT_CRS_STANDARD if hasattr(settings, 'DEFAULT_CRS_STANDARD') else 'EPSG:4326'
qr_packet_size_setting = settings.QR_PACKET_MAX_SIZE_BYTES if hasattr(settings, 'QR_PACKET_MAX_SIZE_BYTES') else 'N/A'

_display_glossary_term(
    "API (Application Programming Interface)", 
    "Rules/protocols for software communication. Used in Sentinel for data sync between tiers (e.g., Facility to Regional) or external system integration (e.g., DHIS2, EMRs).",
    "FHIR_SERVER_ENDPOINT_LOCAL" 
)
_display_glossary_term(
    "CSV (Comma-Separated Values)", 
    "Simple text file format for tabular data. Used for raw data import (e.g., health records) and simple reporting.",
    "HEALTH_RECORDS_CSV_PATH" 
)
_display_glossary_term(
    "FHIR (Fast Healthcare Interoperability Resources)", 
    "Pronounced 'Fire'. HL7® international standard for exchanging EHRs using 'Resources' and an API. Sentinel aims for FHIR support at Tiers 2 & 3.",
    "FHIR_SERVER_ENDPOINT_LOCAL" 
)
_display_glossary_term(
    "GeoJSON", 
    f"Open standard JSON-based format for encoding geographic data (points, lines, polygons) and attributes. Used for operational zone boundaries. Default CRS: {default_crs_setting}.",
    "ZONE_GEOMETRIES_GEOJSON_FILE_PATH" 
)
_display_glossary_term(
    "JSON (JavaScript Object Notation)", 
    "Lightweight, human-readable data-interchange format. Used for configuration files (e.g., escalation protocols) and API data exchange.",
    "ESCALATION_PROTOCOLS_JSON_PATH" 
)
_display_glossary_term(
    "Pictogram", 
    "Simple iconic image representing a concept, action, or object. Used in Sentinel PED UIs for clarity, especially for low-literacy users or multilingual contexts. Mapped via configuration.",
    "PICTOGRAM_MAP_JSON_PATH" 
)
_display_glossary_term(
    "QR Code Packet", 
    f"Method for offline data transfer by encoding data into QR codes. Useful for PED-to-Hub/PED-to-PED exchange. Max single packet size: {qr_packet_size_setting} bytes.",
    "QR_PACKET_MAX_SIZE_BYTES"
)
_display_glossary_term(
    "SQLite", 
    "Embedded SQL database engine. Used in Sentinel for local data storage on PEDs and Supervisor Hubs due to portability and no need for a separate server.",
    "PED_SQLITE_DB_NAME" 
)
_display_glossary_term(
    "TFLite (TensorFlow Lite)", 
    "Open-source deep learning framework for running TensorFlow models on mobile, embedded, and IoT devices. Key for Edge AI on Sentinel PEDs.",
    "EDGE_MODEL_VITALS_DETERIORATION" 
)

# --- Filter and Display ---
query = search_query.lower()
if query:
    filtered_terms = [
        t for t in GLOSSARY_TERMS 
        if query in t['term'].lower() or query in t['definition'].lower() or (t.get('config_key') and query in t['config_key'].lower())
    ]
else:
    filtered_terms = GLOSSARY_TERMS

if not filtered_terms and query:
    st.warning(f"No results found for '{html.escape(query)}'.")

categories = sorted(list(set(t['category'] for t in filtered_terms)))
for category in categories:
    st.header(category)
    for term in filtered_terms:
        if term['category'] == category:
            display_term(term['term'], term['definition'], term.get('config_key'))

st.divider()
st.caption(settings.APP_FOOTER_TEXT)
