# sentinel_project_root/.streamlit/config.toml
# Streamlit application configuration for Sentinel Health Co-Pilot.

# --- Server Configuration ---
[server]
port = 8501
headless = true 
runOnSave = true
maxUploadSize = 50
enableCORS = true 
enableXsrfProtection = true

# --- Browser / Client-Side Configuration ---
# [browser] # This section might be deprecated for some options
# gatherUsageStats = false # This is still valid under [browser]
# initialSidebarState = "expanded" # REMOVE or COMMENT OUT - Handled by st.set_page_config

[browser]
gatherUsageStats = false # This option is generally fine here

# --- Logger Configuration ---
[logger]
level = "info" 

# --- Theme Configuration ---
[theme]
primaryColor = "#1976D2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#343a40"
font = "sans serif"

# --- Mapbox Configuration ---
[mapbox]
# token = "YOUR_MAPBOX_TOKEN" 
