# sentinel_project_root/.streamlit/config.toml
# Streamlit application configuration for Sentinel Health Co-Pilot.

# --- Server Configuration ---
[server]
# Port to run Streamlit on.
port = 8501

# Disable automatic browser opening for server environments; set to false for local dev.
headless = false

# Automatically rerun the script when a source file is saved (recommended for development).
runOnSave = true

# Maximum upload size for st.file_uploader, in megabytes.
maxUploadSize = 50

# Enable Cross-Origin Resource Sharing (CORS) for embedding or cross-domain calls.
enableCORS = true

# Enable XSRF (Cross-Site Request Forgery) protection for security.
enableXsrfProtection = true

# --- Browser / Client-Side Configuration ---
[browser]
# Disable usage statistics for privacy in a sensitive health application.
gatherUsageStats = false

# Initial state of the sidebar ("auto", "expanded", "collapsed").
initialSidebarState = "expanded"

# --- Logger Configuration ---
[logger]
# Logging level for Streamlit's internal logger ("error", "warning", "info", "debug").
level = "info"

# --- Theme Configuration ---
# Custom theme to align with Sentinel's branding (matches settings.py and assets/style_web_reports.css).
[theme]
# Primary accent color for interactive elements (e.g., buttons, sliders).
primaryColor = "#1976D2"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color for sidebar and other UI containers.
secondaryBackgroundColor = "#f8f9fa"

# Text color for main content and most text elements.
textColor = "#343a40"

# Font family for Streamlit components.
font = "sans serif"

# --- Mapbox Configuration ---
[mapbox]
# Mapbox access token should be set via environment variable (MAPBOX_ACCESS_TOKEN) for security.
# Streamlit's st.map and Plotly Express will use the environment variable if set.
